### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by 3xkrazy**
Clarified installing procedures.

### CODE REVIEW

**Comment by gnmmarechal** [comment]
This is still based on the old readme, the new one is the same except for a couple word changes and mistakes corrections.

**Comment by chaoskagami** [comment]
Okay, I'm not comfortable with these documentation changes, and I'll explain why:
- 'agb cetk key' - The cetk is a cetk, not a key. It's a metadata blob. The key is extracted from the cetk but the cetk isn't just a keyfile.
- Line 40-42 - I do feel the native cetk should be mentioned somewhere, but suggesting it is a 'minimum' requirement is wrong. You need a firmkey unless you're rebooting from another CFW.
- These use bullets while not being part of a list. If you'll notice, all other bullets are part of a list, while this commit changes this to be not so.

**Comment by 3xkrazy** [comment]
Regarding 'agb cetk key', it was a typo and I fixed it in commit 2432401.

I'm new to this github thing and used the online web interface to edit. If you want, I can close this pull request.

**Comment by chaoskagami** [comment]
I'll just close it, then. I can tell you were trying to help, though, so thanks. Try not using the web interface. It has the tendency to go haywire. :P

Oh, and in the future - I'd prefer multiple commits to be squashed for future reference if they change the same code. No sense in cluttering the history with minor fixups.

**Comment by ihaveamac** [comment]
small note, github lets you squash commits when you merge a pull request, so manual squashing isn't needed anymore

**Comment by chaoskagami** [comment]
Huh, that's new. Neat.

**Pull request closed without merging**
