### PR TITLE
Corrected typo in README

### PR DESCRIPTION
**Pull request by gnmmarechal**

### CODE REVIEW

**Comment by chaoskagami** [comment]
I'll merge this when I get on my computer for the day.

You know, it's amazing there aren't more typos since I never ran it through spellcheck even once.

**Comment by gnmmarechal** [comment]
I'll see if I can find any more, I just happened to notice this one.

**Comment by gnmmarechal** [comment]
I found a grammar mistake. 

> Its'

is not correct, it should be Its. Changed.

I also did a couple minor changes to words in the text, like romhacks --> ROMhacks, crypto-->encryption, but those are really just my personal preference.

**Comment by chaoskagami** [comment]
Argh. I'm usually very careful with the word 'it.' Well hey, I'm only human.

Also, I agree with the other changes.

**Pull request merged**
