### PR TITLE
Add ability to dump code sections

### PR DESCRIPTION
**Pull request by ghost**
Only for regular titles and demos, not for system titiles/modules

### CODE REVIEW

**Comment by chaoskagami** [comment]
It looks mostly fine, but just a few things:
- The very very high options are meant to stay separate from low options. Can you use 18 instead?
- ~~We're not dumping the whole ExeFS here, are we? I'd prefer a complete dump rather than just the segments, but I suppose it's good enough for now.~~
- On the menu entry, tack an 's' onto the end of the name, and from the description remove 'only'. I'm kinda nitpicking on that, but eh.

EDIT: Also, if you don't feel like changing these, I can merge and make the changes myself if you want. Not a big deal.

**Comment by chaoskagami** [comment]
Y'know, I'll just fix up my qualms. I'm nitpicking, really. Thanks. ;P

(I'll update the credits in the README and on the main post next release.)

**Comment by ghost** [comment]
Oh. I was ready to commit (it was just a text change and change 252 to 18, not that hard lol)

About that second point, I intend this mostly for modifications to RomFS (which can be applied using Corbenik's patch system), like SaltySD and MysteryMachine

**Comment by chaoskagami** [comment]
Sorry. :<

Anyways, I 've rearranged the menus a bit anyways to separate loader options, so it'd probably still get changed regardless.

The MysteryMachine patch you provided to me in PM _does_ work, that said. Maybe use ErrDisp and test again?

I'm looking forward to getting saltySD / overlays eventually. Goodbye NTR, right?

**Comment by ghost** [comment]
Overlays would be the final nail in the coffin

**Comment by chaoskagami** [comment]
Yes, yes they would. And it's most definitely possible. :D

**Pull request merged**
