### PR TITLE
Extend mystery machine patch to Sun & Moon.

### PR DESCRIPTION
**Pull request by kitlith**
Note: I have not tested this myself.

This is based on #40, and seems to be the simple extension of what's already there. We may be able to shorten this by finding "-fushigi.pokemon-gl.com/api/" and seeking back a bit, but that's not the scope of this PR.

Speaking of PR scopes, this PR does not include a patch for no-outlines. I'd like to make that patch more dynamic, so that it works on all of the recent pokemon games. This PR also doesn't include a patch for the QR stuff. (I will note that I have not been able to get that to work as a corbenik patch yet, but I'm not going to give up on it.) Hopefully, these will come as part of a later PR.

### CODE REVIEW

**Comment by chaoskagami** [comment]
I see no reason this shouldn't work; it's the same thing as Gray_Jack's patch, except a bit cleaner in implementation. It was either split all the Pokemon patches out to be separate or merge into the existing one.

I'll merge this; if you get the QR stuff working or a multi-game no-outline, feel free to submit those as another PR. ;)

**Comment by GrayJack** [comment]
I initially tried to make only one, but I failed miserably xD
So I made a temporary one, separated from the original one, but I didn't want to pull request that time, I did it by mistake (sorry, I'm still not used to git and github).
I intended to do that after my exams next week and then pull request.
Well... I didn't know what mean eq|ne|lt|gt|f|nf too, I was going to ask you that next week as well (sorry again, English is not my first language and I couldn't deduce what each one means)

Btw, awesome work Kitling

**Comment by kitlith** [comment]
Uh, thank you, @GaryJack? I take it that this actually works, and you've tested it?

Honestly though, I'll defer all credit to chaoskagami for creating this VM in such a way that it's usable for this, and to Wolfvak for the original patch. And to you, because I only did it because you brought it up. Thanks a bunch, everyone!

**Comment by GrayJack** [comment]
Yeah, it works perfectly @kitling 

As for the no outlines patch, chaoskagami said that if I like I could make a new pull request only for that, but I found out 3 days ago that you already made it before me (I was looking for more info about the qr patches I found your gist) and it was made exactly the same way, so I fell like you should do the pull request for that patch too, even if it's a temporary one, if you like, of course   :)

**Comment by chaoskagami** [comment]
For educational purposes @GrayJack; le|gt|eq|nf etc cause conditional execution depending on the current flags. Those are set by other opcodes such as find and cmp. jmpf means "jump if found flag is set" and otherwise, it simply proceeds to the next opcode.

Roughly speaking, you could probably represent the logic somewhat like this in higher level psuedo-C:

```
char* found;
if (find("https://3ds1-fushigi.pokemon-gl.com/api/", &found)) {
} else if (find("https://3ds2-fushigi.pokemon-gl.com/api/", &found)) {
} else if (find("https://3ds3-fushigi.pokemon-gl.com/api/", &found)) {
} else {
    abort();
}
strcpy(found, "http://mys.salthax.org/api/");
```

That said, the VM is still shittily implemented as-is. For example, conditionals can only be applied to jmp/abort. And don't get me started on the lack of stack or registers...

**Pull request merged**
