### PR TITLE
Crystal the Glaceon got her username changed.

### PR DESCRIPTION
**Pull request by hobbledehoy899**

### CODE REVIEW

**Comment by chaoskagami** [comment]
It'd be far preferrable to use her github handle: @CrystaltheGlaceon

Either way, I'm not too keen on merging changes to the credits at this point. No new code has been added so it strikes me as rather moot in the greater scheme of things. Closing.

**Comment by thetruecatboy** [comment]
Being that this project is both inactive and predates the username change, I don't see a reason to change the credits. That just gives the false impression that this project is still being continued and that's unfair to both Chaos and the userbase.

**Comment by chaoskagami** [comment]
I'm glad we're on the same page here. Then again, we usually are. :P

**Comment by thetruecatboy** [comment]
Although to anyone who has forked this, it would be nice for them to either change it to "Lilith Valentine" or credit my github handle. It's not really that important to do so, but would it be appropriate.
Although I won't press the issue because it's still the same account and it's not like anyone who's used this won't know who I am.

**Pull request closed without merging**
