### PR TITLE
Patches for Pokemon Sun and Moon

### PR DESCRIPTION
**Pull request by GrayJack**
Just made a patch based of the MysteryMachine code made by @Wolfvak and with his explanation on GBATemp

### CODE REVIEW

**Comment by kitlith** [comment]
So far as I can tell, you could extend Wolfvak's patch a little bit more and make one patch that is general to all versions of the game. Is there any particular reason you didn't do that?

**Comment by ghost** [comment]
Seeing the current VM improvements (such as jumps) it's definitely possible to merge Mystery Machine for all games. After all, only one or two URLs differ ("https://3ds3-fushigi.pokemon-gl.com/api/" and "https://npdl.cdn.nintendowifi.net/p01/nsa/%s/%s/%s/%s")

FYI - try to squash "useless" commits like renames, it'll look much better when it's merged.

**Comment by chaoskagami** [comment]
Sorry for lateness (a SSD failure, family shit and Thanksgiving hit hard) but yes, as @Wolfvak and @Kitlith stated, I'd prefer mysterymachine folded into the current patch. There's absolutely no reason for it to be separate.

As for outlines, that's fine as-is, but *technically* you have been beaten to the punch on that one. I'm waiting on the QR code patch to receive some cleanup.

**Comment by chaoskagami** [comment]
Closing, as Kitlith's version has been merged instead.

If you'd like to cut this down to no-outlines only and resubmit, I'd be glad to merge just that until Kitlith manages to make a multi-game patch. Preferably pre-squashed because Github's merge functionality screws history with squashing.

**Pull request closed without merging**
